In [3]:
import torch.optim as optim
import torch.nn as nn
import torch

In [4]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        # super메서드를 사용하면 부모클래스의 __init__메서드를 먼저 호출하고! 그 다음에 자식 클래스의 __init__를 진행
        # 요거 중요하다!!
        self.fc1 = nn.Linear(3,5)
        self.activation = nn.ReLU()
        self.fc2 = nn.Linear(5,5)
        self.outputact = nn.Softmax()
        

        #init에서는 *객체*를 만드는 거야
        #근데 무슨 객체냐? - 앞으로 너가 사용할 함수, 신경망 노드들등 모든 것에 대한 객체
        # 소프트맥스, 렐루, 노드 갯수 등 전부 다 만들어야 돼 

    def forward(self, x):
        x = self.fc1(x)
        x = self.activation(x)
        x = self.fc2(x)
        x = self.outputact(x)
        return x

model = MyModel()
# 각 계층의 편향과 가중치를 확인할 수 있는 메서드
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.1876, -0.2788, -0.4681],
                      [ 0.0298,  0.0144, -0.1137],
                      [ 0.1498,  0.3325,  0.2366],
                      [ 0.0564,  0.1729,  0.2615],
                      [-0.5598,  0.2199,  0.3525]])),
             ('fc1.bias',
              tensor([-0.2977, -0.0252, -0.1398,  0.1540, -0.2365])),
             ('fc2.weight',
              tensor([[ 0.2909, -0.3030, -0.2842,  0.3555, -0.3702],
                      [-0.4318,  0.2615,  0.4240, -0.3208,  0.0903],
                      [ 0.0048, -0.3245,  0.4463, -0.1933, -0.3433],
                      [ 0.4344, -0.0594,  0.3453,  0.2221,  0.0484],
                      [ 0.3151, -0.1254,  0.2848, -0.0801, -0.2222]])),
             ('fc2.bias',
              tensor([-0.2411,  0.3432, -0.3310,  0.3937,  0.1660]))])

In [13]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01, momentum=0.9)
scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer, lr_lambda= lambda epoch:0.95 **epoch)

In [ ]:
for epoch in range(1,100+1):
    for x, y in dataloader:
        optimizer.zero_grad()
        loss_fn(model(x),y).backward()
        optimizer.step()
    scheduler.step()

NameError: name 'dataloader' is not defined